name: Download YouTube Subtitle

on:
  workflow_dispatch:

jobs:
  download-subtitle:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow pushing changes to the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Write YOUTUBE_COOKIES to cookies.txt
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Add jobs.json to the workspace
        run: echo "${{ secrets.JOBS_JSON }}" > jobs.json  # If the jobs.json is stored in GitHub Secrets

      - name: Run download script
        run: python download_sub.py

      - name: Zip subtitles
        run: |
          mkdir -p output
          mv *.vtt output/ || true
          cd output
          zip subtitles.zip *.vtt || echo "No subtitles to zip"
          cd ..

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/subtitles.zip
          git commit -m "Add zipped subtitles [auto]" || echo "Nothing to commit"
          git push
