name: Download and Upload YouTube Subtitle to Mega

on:
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]  # Limit to 4 parallel jobs for testing
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install yt-dlp and Mega-X
        run: |
          pip install yt-dlp mega-x

      - name: Write YOUTUBE_COOKIES to cookies.txt
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Run download and upload script
        run: python download_sub.py ${{ matrix.job_index }}

